// Copyright 2026 Clu and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

type Client struct {
	ClientID   int    `json:"ClientID"`
	ClientName string `json:"ClientName"`
	City       string `json:"City"`
	ZipCode    string `json:"ZipCode"`
	Address    string `json:"Address"`
	Website    string `json:"Website"`
}

type CodesContent struct {
	Id string `json:"Id"`
}

type Job struct {
	Id int `json:"Id"`
}

type Product struct {
	ProductID   int    `json:"ProductID"`
	ProductName string `json:"ProductName"`
}

type SearchResponse struct {
	NumberOfHits int `json:"NumberOfHits"`
}

type State struct {
	StateID           int    `json:"StateID"`
	StateName         string `json:"StateName"`
	StateAbbreviation string `json:"StateAbbreviation"`
}

type TocNode struct {
	Id      string `json:"Id"`
	Heading string `json:"Heading"`
}
