// Copyright 2026 Clu and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newStatesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "states",
		Short:       "US states available in Municode",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newStatesByAbbrCmd(flags))
	cmd.AddCommand(newStatesListCmd(flags))
	return cmd
}
